package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"github.com/spf13/cobra"
)

var envCmd = &cobra.Command{
	Use:   "env",
	Short: "Manage .env files (pull/push)",
}

func init() {
	envCmd.AddCommand(envPullCmd)
	envCmd.AddCommand(envPushCmd)
}

var envPullCmd = &cobra.Command{
	Use:   "pull",
	Short: "Pull secrets to a .env file",
	Run: func(cmd *cobra.Command, args []string) {
		slug := getProjectSlug()
		env, _ := cmd.Flags().GetString("env")
		output, _ := cmd.Flags().GetString("output")
		client := newAuthClient()

		sp := startSpinner(fmt.Sprintf("Pulling %s secrets...", env))

		// List secrets
		body, _, err := client.request("GET", fmt.Sprintf("/api/v1/projects/%s/secrets?environment=%s", slug, env), nil)
		if err != nil {
			sp.fail("Failed: " + err.Error())
			os.Exit(1)
		}

		var secrets []struct {
			KeyName string `json:"key_name"`
		}
		json.Unmarshal(body, &secrets)

		if len(secrets) == 0 {
			sp.stop("No secrets found")
			return
		}

		// Fetch values
		var lines []string
		for _, s := range secrets {
			valBody, _, err := client.request("GET",
				fmt.Sprintf("/api/v1/projects/%s/secrets/%s?environment=%s", slug, s.KeyName, env), nil)
			if err != nil {
				continue
			}
			var val struct {
				Value string `json:"value"`
			}
			json.Unmarshal(valBody, &val)
			lines = append(lines, fmt.Sprintf("%s=%s", s.KeyName, val.Value))
		}

		sort.Strings(lines)

		content := fmt.Sprintf("# Generated by Envault (%s)\n# Project: %s\n\n", env, slug)
		for _, l := range lines {
			content += l + "\n"
		}

		if err := os.WriteFile(output, []byte(content), 0600); err != nil {
			sp.fail("Failed to write file: " + err.Error())
			os.Exit(1)
		}
		sp.stop(fmt.Sprintf("Pulled %d secrets to %s", len(lines), output))
	},
}

func init() {
	envPullCmd.Flags().String("env", "development", "Environment")
	envPullCmd.Flags().StringP("output", "o", ".env", "Output file path")
}
